### ISSUE TITLE
Missing keys.cs

### ISSUE THREAD

**Issue by mmcarson** [ajsmithsw/PlacesSearchBar#1]

**Comment by ajsmithsw** [comment]
To run the example projects you'll need to replace the reference to 'Keys.cs' with either a class of your own or provide the Google Places API key using a string value. It's not possible to provide you with a test key, I'm afraid.

https://github.com/ajsmithsw/PlacesSearchBar/blob/master/PlacesBarExamples/PlacesBarExamples/PlacesBarExamplesPage.xaml.cs#L8 :

`string GooglePlacesApiKey = Keys.ApiKey;  // Replace this with your api key`
