### ISSUE TITLE
Giving me an error

### ISSUE THREAD

**Issue by esolzDotnet** [ajsmithsw/PlacesSearchBar#10]
I have implemented your exact code with my created google api key.

But it's giving me error- System.InvalidCastException: Specified cast is not valid

the error is throwing when i am trying to open the page.

What's the issue here?

**Comment by ajsmithsw** [comment]
Try implementing the namespace as follows:

xmlns:custom="clr-namespace:DurianCode.PlacesSearchBar;assembly=DurianCode.PlacesSearchBar"

There are known issues with latest versions of Xamarin Forms. If you manage to fix your problem and find that it’s related to code then please raise a pull request

**Comment by esolzDotnet** [comment]
yes.
this is my namespace.but same error.

**Comment by esolzDotnet** [comment]
hey still the same issue am facing..any solution ?
