### ISSUE TITLE
Is it possible to get a Place_ID from user-entered text? 

### ISSUE THREAD

**Issue by stavroaudi** [ajsmithsw/PlacesSearchBar#15]
Is it possible to get the user's input and get the place_ID based on user's input without the prediction? I'm using my own searchbar and just need the Places.GetPlace so I need the place_ID. 

At the moment I'm trying a workaround by getting the results list first prediction and retrieving the place ID for that, but still can't do it.

**Comment by ajsmithsw** [comment]
@stavroaudi these are different Google API calls, and not quite what this library was intended for. If you find a solution, feel free to raise a PR :)

Thanks
