### ISSUE TITLE
Clearing Search Box Unfocuses Element

### ISSUE THREAD

**Issue by sirwes** [ajsmithsw/PlacesSearchBar#16]
When you hit the 'x' in the search box, the box is unfocused before it is cleared. Ideally this would just clear the text. Is there something already implemented that fixes this? Or to clear the text before it unfocuses? Or make it so I can handle the click with another function?

**Comment by ajsmithsw** [comment]
@sirwes This does not sound like an issue caused by this library (this library extends the standard Xamarin.Forms search bar). If you believe otherwise then please request that this issue be reopened, with as much detail as possible.

Thanks
