### ISSUE TITLE
Null object reference with invalid or cleared input

### ISSUE THREAD

**Issue by sirwes** [ajsmithsw/PlacesSearchBar#20]
I seem to be getting a null object reference when I type any improper address and hit search (instead of clicking one of the options) and then click back into the search bar. I checked all of my values, and none of them are null. Any ideas??
I also get this error if I type anything in, clear my selection, and click on the search bar again

**Comment by ajsmithsw** [comment]
Hi @sirwes ,

Please could you provide steps to reproduce, and the full stack trace for the crash?
