### ISSUE TITLE
Error Limit

### ISSUE THREAD

**Issue by ivanteles** [ajsmithsw/PlacesSearchBar#22]
It happens with a single research, how to solve?

{
   "error_message" : "You have exceeded your daily request quota for this API. If you did not set a custom daily request quota, verify your project has an active billing account: http://g.co/dev/maps-no-account",
   "predictions" : [],
   "status" : "OVER_QUERY_LIMIT"
}

**Comment by ajsmithsw** [comment]
Check that you have a valid API key, for the correct Google API (see README), and use the google console to review the calls that have been made, you might find out that you have reached your limit. You can increase your limit by adding your billing information.

Please reopen this issue if you discover that the issue is caused by the PlacesSearchBar library and not by Google. Thanks

**Comment by ivanteles** [comment]
I am using a valid key yes.
On the border error I saw in the google dashboard that I made 8 requests and of those 8 7 returned errors. The one from query_limit.
From what I've been researching, it seems that the way it is implemented, its code makes many requests and the time between one call and another is very short, so google is blocking the calls. so I am studying a way around this.
another tip is to implement in the code the use of the variable session_token so that one has a low billing, this I have already done. Then I'll have to do a pull!

**Comment by ajsmithsw** [comment]
@ivanteles I have just tested the latest NuGet against my test project using a valid API key and I am not seeing the same issue. Please could you provide detailed steps to reproduce?

The specific API key you need is for 'Google Places API Web Service'.

**Comment by ivanteles** [comment]
The problem is that google warns you that you have a 100k limit available.
The detail is in: these 100k is only available when billing is activated, without activating billing the limit drops to 1.
I would never imagine that.
But it's settled!

The tip is for anyone to go through the same problem

**Comment by ajsmithsw** [comment]
@ivanteles thanks for pointing this out! Seems Google may have changed their free usage policy. Good news is that by setting up billing you can overcome the issue.

If you'd like to update the README to reflect this and raise a PR, go ahead :)

**Comment by ivanteles** [comment]
As I told you in the opening of the post.
I also implemented session token usage to reduce the number of uses.
I'll send a pull as soon as I have a little time.
