### ISSUE TITLE
API Key not protected

### ISSUE THREAD

**Issue by albernazf** [ajsmithsw/PlacesSearchBar#25]
I wanted to use it but it is not possible to protect the API key because you need a browser API key and the request is comming from a mobile phone so you can't block requests using CORS.
The only way to block unwanted requests is using for IOS the bundle and android the sha1 finger print.
I imagine that's because this implementation is using simple httpclient to connect to the API instead of using Google SDK.

**Comment by albernazf** [comment]
I'll fork this repo and implement the google SDK once I have that done I'll create a PR.

Cheers guys

**Comment by ajsmithsw** [comment]
Hi @albernazf, many thanks for your support. Indeed since the library was created there are now officially supported google SDKs for Xamarin. If you’re successful implementing those then do please raise a PR and I’ll review!
