### ISSUE TITLE
Response Language

### ISSUE THREAD

**Issue by iglesiasfernando** [ajsmithsw/PlacesSearchBar#29]
Hi! Is there a way to change the response language? I need the response in spanish

**Comment by Almazidi** [comment]
Hence it is actually to be composed as a uri you can attach language parameter or any other optional parameters. ((as a temp solution use something like this ))
`	search_bar.ApiKey = GooglePlacesApiKey+"&language=ar";`

ar for Arabic Language respond

refer to this for more details
[https://developers.google.com/places/web-service/search](url)
