### ISSUE TITLE
Set up a Country 

### ISSUE THREAD

**Issue by gravitpt** [ajsmithsw/PlacesSearchBar#6]
Is it possible set up a unique country of search?

**Comment by ajsmithsw** [comment]
@gravitpt Google uses the IP address of the http request to bias the region. But you can set LocationBias on the Places Search Bar.

**Comment by mikecamimo** [comment]
Hi Alex,
I've tested this out and the IP address bias doesn't seem to work very well, and the LocationBias is only really useful if you know the radius. It would be great if the PlacesSearchBar supported the 'components' parameter, through which you could pass in a country list. 
Is this a possibility ? 
Cheers,
Michael

**Comment by ajsmithsw** [comment]
@gravitpt apologies for closing this issue too early - thanks again to @mikecamimo for adding the ```component``` feature to make this easier.
