### ISSUE TITLE
LocationBias double formatting

### ISSUE THREAD

**Issue by jochembroekhoff** [ajsmithsw/PlacesSearchBar#8]
In some cultures, the LocationBias ToString() method returns a string with commas instead of dots.
I'd suggest making use of the `double.ToString(CultureInfo);` method and passing `CultureInfo.InvariantCulture` as its argument.

Example:
```csharp
return string.Format("&location={0},{1}&radius={2}", latitude.ToString(CultureInfo.InvariantCulture),
		        longitude.ToString(CultureInfo.InvariantCulture), radius);
```

**Comment by eminbayrak** [comment]
@jochembroekhoff Could you please confirm if the search bar still appears on phones/emulator with different resolution. I cannot make it displayed on some phones that have low resolution.

**Comment by jochembroekhoff** [comment]
What has this to do with this issue?

**Comment by ajsmithsw** [comment]
@jochembroekhoff please could you raise a pull request?

**Comment by ajsmithsw** [comment]
@eminbayrak If you have issues and you cannot fix the problem yourself, please raise a separate github issue. Pull requests are welcome :)

**Comment by ajsmithsw** [comment]
Many thanks for your contribution! I’m converting this to a .NET Standard library so it’s compatible with newer versions of Xamarin Forms. WIP
