### ISSUE TITLE
PlacesSearchBar entry box won't displayed on some phones.

### ISSUE THREAD

**Issue by eminbayrak** [ajsmithsw/PlacesSearchBar#9]
I tried the plugin on 4 different phones (2 physicals + 2 emulators), and two of them did not display the PlacesSearchBar entry box.

![issue](https://user-images.githubusercontent.com/32653645/39221797-1cfd212c-4807-11e8-9e85-f13ad86327b2.PNG)

**Comment by ajsmithsw** [comment]
@eminbayrak try using a default search bar to rule out issues with your layout. I can't offer customer support on this library, if you manage to solve the problem please raise a PR :)

**Comment by eminbayrak** [comment]
Defining HeightRequest resolves the problem.

<places:PlacesBar x:Name="search_bar" **HeightRequest="50"** Placeholder="Search ..." />
